# Generated by Django 4.0.5 on 2022-07-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('emailid', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
