# Generated by Django 4.0.5 on 2022-07-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_studentdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='EmployeDeatils',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
