# Generated by Django 4.0.5 on 2022-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_studentdetails_employedeatils_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('emailid', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeDeatils',
        ),
    ]
