# Generated by Django 4.0.5 on 2022-07-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_studentdetails_delete_employedeatils'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
