# Generated by Django 4.0.5 on 2022-07-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_studentemail_delete_studentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEmail',
        ),
    ]
