# Generated by Django 4.0.5 on 2022-07-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0006_delete_studentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('genter', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('join_date', models.IntegerField()),
            ],
        ),
    ]
