# Generated by Django 4.0.5 on 2022-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='join_date',
            field=models.DateField(),
        ),
    ]
