# Generated by Django 4.0.5 on 2022-07-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_studentlist_email_alter_studentlist_join_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentList',
        ),
    ]
