# Generated by Django 4.0.5 on 2022-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('genter', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Emailsent',
        ),
    ]
