# Generated by Django 4.0.5 on 2022-07-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_studentlist_delete_emailsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('count', models.IntegerField(default=0)),
                ('user_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
